version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./backend/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password


  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
  
  front:
    build: .
    volumes:
      - ./frontend:/app
    command: sh -c "cd app && yarn && yarn start"
    ports:
      - "4000:3000"
    
volumes:
  mysql-data: